code --install-extension analytic-signal.preview-pdf
code --install-extension austenc.tailwind-docs
code --install-extension batisteo.vscode-django
code --install-extension bracketpaircolordlw.bracket-pair-color-dlw
code --install-extension bradlc.vscode-tailwindcss
code --install-extension christian-kohler.path-intellisense
code --install-extension codeium.codeium
code --install-extension codezombiech.gitignore
code --install-extension codium.codium
code --install-extension ctcuff.font-preview
code --install-extension cweijan.epub-reader
code --install-extension dart-code.dart-code
code --install-extension dart-code.flutter
code --install-extension davidanson.vscode-markdownlint
code --install-extension dbaeumer.vscode-eslint
code --install-extension dlasagno.wal-theme
code --install-extension donjayamanne.githistory
code --install-extension dracula-theme.theme-dracula
code --install-extension eamodio.gitlens
code --install-extension ecmel.vscode-html-css
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.auto-close-tag
code --install-extension github.copilot
code --install-extension github.copilot-chat
code --install-extension htmlhint.vscode-htmlhint
code --install-extension jock.svg
code --install-extension kevinrose.vsc-python-indent
code --install-extension kisstkondoros.vscode-gutter-preview
code --install-extension mathematic.vscode-latex
code --install-extension mdickin.markdown-shortcuts
code --install-extension mechatroner.rainbow-csv
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.black-formatter
code --install-extension ms-python.debugpy
code --install-extension ms-python.isort
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-toolsai.vscode-jupyter-cell-tags
code --install-extension ms-toolsai.vscode-jupyter-slideshow
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode.cmake-tools
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.cpptools-extension-pack
code --install-extension ms-vscode.cpptools-themes
code --install-extension ms-vscode.remote-explorer
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension njpwerner.autodocstring
code --install-extension oderwat.indent-rainbow
code --install-extension pkief.material-icon-theme
code --install-extension ritwickdey.liveserver
code --install-extension shakram02.bash-beautify
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension streetsidesoftware.code-spell-checker-italian
code --install-extension twxs.cmake
code --install-extension visualstudioexptteam.intellicode-api-usage-examples
code --install-extension visualstudioexptteam.vscodeintellicode
code --install-extension wakatime.vscode-wakatime
code --install-extension yzane.markdown-pdf
code --install-extension yzhang.markdown-all-in-one
code --install-extension zhyong10.markdown-html
