#! /bin/sh

# Variables
IMAGE="$HOME/wallpaper/waves.png"

# Check for external monitor 
if xrandr -q | grep 'HDMI-1-0 connected'; then
xrandr --output HDMI-1-0 --primary --mode 3440x1440 --rotate normal --output eDP-1 --off
bspc monitor HDMI-1-0 -d ◇ ◇ ◇ ◇ ◇ ◇ ◇ ◇
else
bspc monitor eDP-1 -d  󰡘     󰡘 
fi

# If sxhkd isn't running, start it
pgrep -x sxhkd > /dev/null || sxhkd &

bspc config border_width         0
bspc config window_gap          25

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner

# Set wallpaper
feh --bg-fill $IMAGE

# Start compositor
picom --config $HOME/.config/picom.conf -b --experimental-backends

# Start polybar
$HOME/.config/polybar/launch.sh &

# Start screensaver
# xscreensaver -nosplash